name: 'Spark 1 n0s1'
description: 'Scan Project Management platforms (e.g. Jira, Linear) for secret leaks with n0s1'
author: 'Spark 1'
inputs:
  scan-target:
    description: 'Scan target platform to use for scanning secret leaks'
    required: true
    default: 'jira_scan'
  user-email:
    description: 'User email for target platform login'
    required: false
    default: ''
  password-key:
    description: 'User password or API key'
    required: false
    default: ''
  platform-url:
    description: 'Your Jira instance URL'
    required: false
    default: ''
  post-comment:
    description: 'Add a comment alerting about the leak to the ticket with the sensitive data'
    required: false
    default: ''
  skip-comment:
    description: 'Do not search for sensitive data at the tickets comment'
    required: false
    default: ''
  regex-file:
    description: 'Path to a custom regex configuration file'
    required: false
    default: ''
  config-file:
    description: 'Path to a custom scanning configuration file'
    required: false
    default: ''
  report-file:
    description: 'Path to output file'
    required: false
    default: ''
  secret-manager:
    description: 'Secret manager tool name to be suggested when leaks are found'
    required: false
    default: ''
  contact-help:
    description: 'Contact information for assistance when leaks are detected'
    required: false
    default: ''
  label:
    description: 'Unique identifier for n0s1 bot comments'
    required: false
    default: ''
  show-matched-secret-on-logs:
    description: 'Write actual leaked secret to reports and logs'
    required: false
    default: ''
  ai-analysis:
    description: 'Send scan results to an AI agent to validate leaked credentials'
    required: false
    default: ''
  private:
    description: 'Private mode disables all interaction with the n0s1 backend service'
    required: false
    default: ''
  debug:
    description: 'Debug mode. Warning it may further expose sensitive data'
    required: false
    default: ''
  report-format:
    description: 'Output report format. Supported formats: n0s1, SARIF, gitlab'
    required: false
    default: ''
  timeout:
    description: 'HTTP request timeout in seconds'
    required: false
    default: ''
  limit:
    description: 'The limit of the number of pages to return per HTTP request'
    required: false
    default: ''
  insecure:
    description: 'Insecure mode. Ignore SSL certificate verification'
    required: false
    default: ''
  map:
    description: 'Enable mapping mode and define how many levels for the mapping'
    required: false
    default: ''
  map-file:
    description: 'Path to map file (e.g. n0s1_map.json)'
    required: false
    default: ''
  scope:
    description: 'Define a chunk of the map file to be scanned. Ex: 3/4'
    required: false
    default: ''
  owner:
    description: 'GitHub owner (e.g. user or organization)'
    required: false
    default: ''
  repo:
    description: 'GitHub repository to be scanned'
    required: false
    default: ''
  branch:
    description: 'GitHub/GitLab repository branch to be scanned'
    required: false
    default: ''
runs:
  using: 'docker'
  image: "Dockerfile"