#!/bin/bash
set -e

# GitHub Actions injects these automatically as INPUT_* vars
SCAN_TARGET="${INPUT_SCAN-TARGET}"
USER_EMAIL="${INPUT_USER-EMAIL}"
PASSWORD_KEY=$(echo "${INPUT_PASSWORD-KEY}" | tr -d " ")
PLATFORM_URL="${INPUT_PLATFORM-URL}"
POST_COMMENT="${INPUT_POST-COMMENT}"
SKIP_COMMENT="${INPUT_SKIP-COMMENT}"
REGEX_FILE="${INPUT_REGEX-FILE}"
CONFIG_FILE="${INPUT_CONFIG-FILE}"
REPORT_FILE="${INPUT_REPORT-FILE:-n0s1_report.json}"
SECRET_MANAGER="${INPUT_SECRET-MANAGER}"
CONTACT_HELP="${INPUT_CONTACT-HELP}"
LABEL="${INPUT_LABEL}"
SHOW_MATCHED="${INPUT_SHOW-MATCHED-SECRET-ON-LOGS}"
DEBUG="${INPUT_DEBUG}"
REPORT_FORMAT="${INPUT_REPORT-FORMAT}"
TIMEOUT="${INPUT_TIMEOUT}"
LIMIT="${INPUT_LIMIT}"
INSECURE="${INPUT_INSECURE}"
MAP="${INPUT_MAP}"
MAP_FILE="${INPUT_MAP-FILE}"
SCOPE="${INPUT_SCOPE}"
OWNER="${INPUT_OWNER}"
REPO="${INPUT_REPO}"
BRANCH="${INPUT_BRANCH}"
PRIVATE="${INPUT_PRIVATE}"

ARGS=""
[ -n "$USER_EMAIL" ]     && ARGS="$ARGS --email $USER_EMAIL"
[ -n "$PASSWORD_KEY" ]   && ARGS="$ARGS --api-key $PASSWORD_KEY"
[ -n "$PLATFORM_URL" ]   && ARGS="$ARGS --server $PLATFORM_URL"
[ -n "$POST_COMMENT" ]   && ARGS="$ARGS --post-comment"
[ -n "$SKIP_COMMENT" ]   && ARGS="$ARGS --skip-comment"
[ -n "$REGEX_FILE" ]     && ARGS="$ARGS --regex-file $REGEX_FILE"
[ -n "$CONFIG_FILE" ]    && ARGS="$ARGS --config-file $CONFIG_FILE"
[ -n "$REPORT_FILE" ]    && ARGS="$ARGS --report-file $REPORT_FILE"
[ -n "$SECRET_MANAGER" ] && ARGS="$ARGS --secret-manager $SECRET_MANAGER"
[ -n "$CONTACT_HELP" ]   && ARGS="$ARGS --contact-help $CONTACT_HELP"
[ -n "$LABEL" ]          && ARGS="$ARGS --label $LABEL"
[ -n "$SHOW_MATCHED" ]   && ARGS="$ARGS --show-matched-secret-on-logs"
[ -n "$DEBUG" ]          && ARGS="$ARGS --debug"
[ -n "$REPORT_FORMAT" ]  && ARGS="$ARGS --report-format $REPORT_FORMAT"
[ -n "$TIMEOUT" ]        && ARGS="$ARGS --timeout $TIMEOUT"
[ -n "$LIMIT" ]          && ARGS="$ARGS --limit $LIMIT"
[ -n "$INSECURE" ]       && ARGS="$ARGS --insecure"
[ -n "$MAP" ]            && ARGS="$ARGS --map $MAP"
[ -n "$MAP_FILE" ]       && ARGS="$ARGS --map-file $MAP_FILE"
[ -n "$SCOPE" ]          && ARGS="$ARGS --scope $SCOPE"
[ -n "$OWNER" ]          && ARGS="$ARGS --owner $OWNER"
[ -n "$REPO" ]           && ARGS="$ARGS --repo $REPO"
[ -n "$BRANCH" ]         && ARGS="$ARGS --branch $BRANCH"
[ -n "$PRIVATE" ]        && ARGS="$ARGS --private"

echo "Running n0s1 with options: n0s1 ${SCAN_TARGET} ${ARGS}" | sed "s/$PASSWORD_KEY/<REDACTED>/g"
n0s1 ${SCAN_TARGET} ${ARGS}