#!/bin/bash
set -e

# GitHub Actions injects these automatically as INPUT_* vars
SCAN_TARGET="$(printenv 'INPUT_SCAN-TARGET')"
USER_EMAIL="$(printenv 'INPUT_USER-EMAIL')"
PASSWORD_KEY="$(printenv 'INPUT_PASSWORD-KEY' | tr -d ' ')"
PLATFORM_URL="$(printenv 'INPUT_PLATFORM-URL')"
POST_COMMENT="$(printenv 'INPUT_POST-COMMENT')"
SKIP_COMMENT="$(printenv 'INPUT_SKIP-COMMENT')"
REGEX_FILE="$(printenv 'INPUT_REGEX-FILE')"
CONFIG_FILE="$(printenv 'INPUT_CONFIG-FILE')"
REPORT_FILE="$(printenv 'INPUT_REPORT-FILE')"
SECRET_MANAGER="$(printenv 'INPUT_SECRET-MANAGER')"
CONTACT_HELP="$(printenv 'INPUT_CONTACT-HELP')"
LABEL="$(printenv 'INPUT_LABEL')"
SHOW_MATCHED="$(printenv 'INPUT_SHOW-MATCHED-SECRET-ON-LOGS')"
DEBUG="$(printenv 'INPUT_DEBUG')"
REPORT_FORMAT="$(printenv 'INPUT_REPORT-FORMAT')"
TIMEOUT="$(printenv 'INPUT_TIMEOUT')"
LIMIT="$(printenv 'INPUT_LIMIT')"
INSECURE="$(printenv 'INPUT_INSECURE')"
MAP="$(printenv 'INPUT_MAP')"
MAP_FILE="$(printenv 'INPUT_MAP-FILE')"
SCOPE="$(printenv 'INPUT_SCOPE')"
OWNER="$(printenv 'INPUT_OWNER')"
REPO="$(printenv 'INPUT_REPO')"
BRANCH="$(printenv 'INPUT_BRANCH')"
PRIVATE="$(printenv 'INPUT_PRIVATE')"
AI_ANALYSIS="$(printenv 'INPUT_AI-ANALYSIS')"

ARGS=""
[ -n "$USER_EMAIL" ]     && ARGS="$ARGS --email $USER_EMAIL"
[ -n "$PASSWORD_KEY" ]   && ARGS="$ARGS --api-key $PASSWORD_KEY"
[ -n "$PLATFORM_URL" ]   && ARGS="$ARGS --server $PLATFORM_URL"
[ -n "$POST_COMMENT" ]   && ARGS="$ARGS --post-comment"
[ -n "$SKIP_COMMENT" ]   && ARGS="$ARGS --skip-comment"
[ -n "$REGEX_FILE" ]     && ARGS="$ARGS --regex-file $REGEX_FILE"
[ -n "$CONFIG_FILE" ]    && ARGS="$ARGS --config-file $CONFIG_FILE"
[ -n "$REPORT_FILE" ]    && ARGS="$ARGS --report-file $REPORT_FILE"
[ -n "$SECRET_MANAGER" ] && ARGS="$ARGS --secret-manager $SECRET_MANAGER"
[ -n "$CONTACT_HELP" ]   && ARGS="$ARGS --contact-help $CONTACT_HELP"
[ -n "$LABEL" ]          && ARGS="$ARGS --label $LABEL"
[ -n "$SHOW_MATCHED" ]   && ARGS="$ARGS --show-matched-secret-on-logs"
[ -n "$DEBUG" ]          && ARGS="$ARGS --debug"
[ -n "$REPORT_FORMAT" ]  && ARGS="$ARGS --report-format $REPORT_FORMAT"
[ -n "$TIMEOUT" ]        && ARGS="$ARGS --timeout $TIMEOUT"
[ -n "$LIMIT" ]          && ARGS="$ARGS --limit $LIMIT"
[ -n "$INSECURE" ]       && ARGS="$ARGS --insecure"
[ -n "$MAP" ]            && ARGS="$ARGS --map $MAP"
[ -n "$MAP_FILE" ]       && ARGS="$ARGS --map-file $MAP_FILE"
[ -n "$SCOPE" ]          && ARGS="$ARGS --scope $SCOPE"
[ -n "$OWNER" ]          && ARGS="$ARGS --owner $OWNER"
[ -n "$REPO" ]           && ARGS="$ARGS --repo $REPO"
[ -n "$BRANCH" ]         && ARGS="$ARGS --branch $BRANCH"
[ -n "$PRIVATE" ]        && ARGS="$ARGS --private"
[ -n "$AI_ANALYSIS" ]    && ARGS="$ARGS --ai-analysis"

LOG_MSG="Running n0s1 with options: n0s1 ${SCAN_TARGET} ${ARGS}"
if [ -n "$PASSWORD_KEY" ]; then
    echo "$LOG_MSG" | sed "s/$PASSWORD_KEY/<REDACTED>/g"
else
    echo "$LOG_MSG"
fi
n0s1 ${SCAN_TARGET} ${ARGS}